[package]
name = "gai-python"
version = "0.1.2"
edition = "2024"
description = "Python bindings for the Genomic Attribute Index"
repository = "https://github.com/Chris7/genomic-attribute-index"
license = "Apache-2.0"
publish = false

[lib]
name = "_gai"
crate-type = ["cdylib"]

[features]
default = []
abi3 = ["pyo3/abi3-py310"]
extension-module = ["pyo3/extension-module"]

[dependencies]
gai = { package = "genomic-attribute-index", version = "0.1.0", path = ".." }
pyo3 = { version = "0.25.1", features = ["multiple-pymethods"] }

[workspace]
members = ["."]
